package com.example.jonathas.splatics;

public class Fases {
    static final String[] FASES = new String[]{"Arowana Mall",
    "Blackbelly Skatepark",
    "Camp Triggerfish",
    "Goby Arena",
    "Humpback Pump Track",
    "Inkblot Art Academy",
    "Kelp Dome",
    "MakoMart",
    "Manta Maria",
    "Moray Towers",
    "Musselforge Fitness",
    "Piranha Pit",
    "Port Mackerel",
    "Shellendorf Institute",
    "Shifty Station1",
    "Shifty Station10",
    "Shifty Station11",
    "Shifty Station2",
    "Shifty Station3",
    "Shifty Station4",
    "Shifty Station5",
    "Shifty Station6",
    "Shifty Station7",
    "Shifty Station8",
    "Shifty Station9",
    "Snapper Canal",
    "Starfish Mainstage",
    "Sturgeon Shipyard",
    "The Reef",
    "Wahoo World",
    "Walleye Warehouse"};
}
